amqp:
  admin:
    auto-create: ${AMQP_ADMIN_AUTO_CREATE:false}
  host: ${AMQP_RABBIT_HOST:localhost}
  port: ${AMQP_RABBIT_PORT:8443}
  username: ${AMQP_RABBIT_USERNAME:adm_videos}
  password: ${AMQP_RABBIT_PASSWORD:123456}

keycloak:
  realm: ${KEYCLOAK_REALM:fc3-codeflix}
  host: ${KEYCLOAK_HOST:http://localhost:8443}

mysql:
  username: ${DATABASE_MYSQL_USERNAME:root}
  password: ${DATABASE_MYSQL_PASSWORD:123456}
  schema: admin_videos
  url: ${DATABASE_MYSQL_URL:localhost:3306}

server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.host}/realms/${keycloak.realm}/protocol/openid-connect/certs
          issuer-uri: ${keycloak.host}/realms/${keycloak.realm}
