#ampq:
#  admin:
#    auto-create: true
#  host: localhost
#  port: 5672
#  username: adm_videos
#  password: 123456
#keycloak:
#  realm: fc3-codeflix
#  host: http://localhost:8443

mysql:
  username: root
  password: 123456
  schema: admin_videos
  url: localhost:3306
#server:
#  port: 8080
#  undertow:
#    threads:
#      worker: 10 # Generally this should be reasonably high, at least 10 per CPU core: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2
#      io: 2 # One IO thread per CPU core is a reasonable default: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration